# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My website
email: ntvbk1024@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Đây là website tôi chia sẻ những gì tôi học được 
baseurl: "" # the subpath of your site, e.g. /blog
url: "vinh1024.github.io" # the base hostname & protocol for your site
twitter_username: vinhbk1024
github_username:  vinh1024

# Build settings
markdown: kramdown
mathjax: true